version: "3.4"
services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "8883:8883"
    volumes:
      - ./config:/mosquitto/config
      - ./certs:/mosquitto/certs
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
