version: '3'
services:
  notebook:
    image: jupyter/pyspark-notebook
    ports:
      - '8888:8888'
    environment:
      - GRANT_SUDO=yes
      - TZ=Asia/Tokyo
    volumes:
      - ./work:/home/jovyan/work
      - ./path:/home/jovyan/path