# src/research_crew/config/tasks.yaml
research_task:

  description: >
    {company}社について徹底的な調査を実施してください。以下の点に着目してください。
    1. 現在の会社の状況と健全性
    2. これまでの会社の業績
    3. 主要な課題と機会
    4. 最近のニュースと出来事
    5. 将来の見通しと潜在的な発展
    調査結果を、明確なセクションを持つ構造化された形式で整理するようにしてください。
    
  expected_output: >
    {company} に関するあらゆる側面を網羅した、整理されたセクション構成の包括的な調査資料。関連する具体的な事実、数値、事例を記載してください。

  agent: researcher

analysis_task:

  description: >
    調査結果を分析し、{company}に関する包括的なレポートを作成してください。レポートは以下の点に留意してください。
    1. エグゼクティブサマリーから始める
    2. 調査で得られたすべての主要情報を含める
    3. トレンドとパターンに関する洞察に満ちた分析を提供する
    4. 企業の市場見通しを提示する（ただし、この見通しは取引の意思決定には使用すべきではないことに留意する）
    5. 明確な見出しを付け、読みやすいプロフェッショナルなスタイルで作成する

  expected_output: >
    {company} に関する洗練されたプロフェッショナルなレポートであり、調査結果に分析と洞察を加えて提示します。
    レポートは、エグゼクティブサマリー、主要セクション、および結論を含む、よく構成されたものである必要があります。

  agent: analyst

  context:
    - research_task

  output_file: output/report.md
